config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords'
  }



  
  root to: 'users#index'
  resources :users  do
    member do
      get 'profile'
    end
  end
  resources :chatrooms do
  resources :messages
  end  
 
end

app/views/shared/_footer.html.erb
<footer class="footer">
 
  <div class="text-center p-3 bg-grey" style="background-color: rgba(0, 0, 0, 0.2); color: white;">
   All right reserved to Copyright © 2023. 
    <a href="<%= root_path %>">support@ichat.pk</a>
  </div>
 
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgba(0, 0, 0, 0.2);">
  <div class="container-fluid">
       <%= link_to root_path, style:'text-decoration:none;' do %>
    <%= image_tag 'logo.png', alt: "Logo", width: "50", height: "50", style: "margin-left: 15px;" %>
    <span style="vertical-align: middle; margin-left: 10px; font-size: 24px;">iChat</span>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <% if user_signed_in? %>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto">
        <a href="<%= profile_user_path(current_user) %>">
        <%= image_tag current_user.avatar_url, class: "img-fluid rounded-circle", 
        style: "width: 40px; height: 40px; border-radius: 100px;" if current_user&.avatar_url? %> </a>
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.full_name %> 
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><hr class="dropdown-divider"></li>
              <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </ul>
        </div>
      </div> 

    <% end %>
  </div>
</nav>